import BottomBar from "@/components/bottombar";
import Navbar from "@/components/navbar";
import Head from "next/head";

const Apples = () => {
  return (
    <>
      <Head>
        <title>APPLES Reflection</title>
      </Head>
      <Navbar />
      <main className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 text-gray-900 p-6 md:p-12">
        <div className="max-w-5xl mx-auto space-y-10">
          
          <section className="text-center">
            <h1 className="text-4xl font-bold mb-4">
            APPLES Reflection
            </h1>
            
          </section>
          <section className="bg-white shadow-lg rounded-2xl p-6 md:p-10 space-y-6">
                <p><b>Prompt:</b> As part of the service-learning component of this course, you are to identify what the goals and values of your project are. Clearly, not all of the projects are out to solve world hunger but they are all meeting some population&apos;s needs. Identify the need that you are meeting. Explain the importance of this need and how the work that you are doing will impact it.</p>
                <p><b>Response:</b> Pediatric dieticians play an essential role in supporting the healthy growth and development of children. However, a large portion of their time and energy is often spent performing manual calculations to determine nutritional needs, searching through multiple resources to find information on different formulas, and comparing the amount of each nutrient in a formula mix to the ideal amounts for a patient. This process is both time-consuming and mentally taxing, contributing to burnout among dieticians who could otherwise devote that energy to direct patient care. </p>
                <p> Our team&apos;s project addresses this need by streamlining and simplifying the most repetitive parts of the dietician’s workflow. It provides a centralized table of product information and automates many of the calculations involved in assessing and planning nutrition. By making these tasks more efficient, the website enables dietitians to focus their time on aspects of their work that can’t be automated, such as creating personalized nutrition plans, communicating with patients and families, managing feeding difficulties, and providing education and counseling to support healthy development.</p>
                <p> The site also includes roles for super users and data entry users, which helps maintain the integrity and safety of the product information available to dieticians. Super users can approve and activate formulas before they become accessible in the product table. Dieticians cannot use formulas until they have been activated, ensuring that only valid and up-to-date products are available for clinical use. This system prevents discontinued or recalled formulas from being used in patient care, protecting both the dietician’s workflow and patient safety.</p>
                <p> Our website not only prevents burnout but also enhances the quality of care by ensuring that dieticians can dedicate more of their attention to the human-centered, decision-making side of their profession. The data and calculations generated by the website also serve as evidence to inform nutritional planning and strengthen clinical decision-making. Our client, a clinical dietician at UNC Children’s Primary Care and Adolescent Medicine, works directly with children and their families to promote healthy growth through individualized nutrition plans. By developing this website, we aim to directly support her and others in her field by reducing the administrative and cognitive burden of their work. Ultimately, our project helps ensure that more of their time and expertise can be devoted to what matters most: improving children’s health outcomes and supporting families in their care.</p>
          </section>

          </div>
</main>
    <BottomBar />
    </>
  );
};

export default Apples;
